### ISSUE TITLE
我在运行exploration.launch时遇到了一些错误

### ISSUE THREAD

**Issue by LiuHeng2099** [bairuofei/Graph-Based_SLAM-Aware_Exploration#1]
作者您好，我在实现功能时出现了一些问题，首先是在offline_tsp_evaluation.py文件中出现了from concorde import Problem, run_concorde报错,我在pyconcorde包中发现了Problem类但是没有找到run_concorde，这确实令我困惑；然后是我发现在exploration.launch中出现了很多需要results文件的地方，但是我在您给出的cpp_solver包中并没有发现results，请问该文件应该如何获得。如果您有时间能够解答我的问题，我将感激不尽！

**Comment by bairuofei** [comment]
Sorry for the late reply and thanks for your interest in our work. 

1. The first problem occurs because you did not install the pyconcorde package correctly. As I mentioned [here](https://github.com/bairuofei/Graph-Based_SLAM-Aware_Exploration?tab=readme-ov-file#requirements), you should not install the stable version of pyconcorde, but another branch called "pyconcorde-subprocess", which offers a function that can accept a distance matrix as input when constructing a TSP problem (, and this function is not supported by the stable version of pyconcorde). You can find the detailed installation guide [here](https://github.com/jvkersch/pyconcorde/issues/28#issuecomment-770354999), as I have provided in README file.

2. The files under the folder "src/" are used to record some data online for evaluation afterwards, and it does not contain any information itself. You can simply create an empty folder called "src" by yourself, or you can set these paths in the `exploration.launch` file to your preferred locations.
